### ISSUE TITLE
Mention Syntax::Highlight::Engine::Kate

### ISSUE THREAD

**Issue by nichtich** [perlancar/perl-SyntaxHighlight-Any#1]
What's the benefit compared to [Syntax::Highlight::Engine::Kate](https://metacpan.org/pod/Syntax::Highlight::Engine::Kate)?

**Comment by perlancar** [comment]
Sorry, missed this PR/issue (didn't receive notification from GitHub).

I've added a link to a 2012 article as well as some related modules. As for SHE:Kate itself, http://cpanratings.perl.org/dist/Syntax-Highlight-Engine-Kate

Thanks!
